### ISSUE TITLE
Preview image view gets smaller after changing front/rear camera

### ISSUE THREAD

**Issue by kerimovscreations** [spinaki/android-camera#6]

**Comment by spinaki** [comment]
front and rear sensors support different preview sizes / aspect ratios since those are different sensors / hardwares. Is this what you are saying ? However I can add APIs to access different preview sizes -- but they will likely be different.

**Comment by kerimovscreations** [comment]
In the first time try, preview works great, but if I switched the camera and try to take a picture, preview layout becomes visible by its half width size and remaining part is cropped. In addition, I've made this activity with full-screen support mode, I think it can cause such a problem.

**Comment by spinaki** [comment]
hi, I added a new V2 API -- with major fixes. Please see the readme. You can now choose the aspect ratio which is good for your camera. Can you please let me know if this bug still exists.
