### ISSUE TITLE
How you close camera

### ISSUE THREAD

**Issue by assasinshark** [spinaki/android-camera#7]
Hi, sorry but I couldn't find a way to close the camera once open, it would be great to have a way of finishing capturing images and hide the views created, the onCameraClosed is called when i change between front and rear camera but there is no way to close the camera after capturing the photo.

**Comment by spinaki** [comment]
I usually use the back button to close -- but I can add an API level endpoint too. coming soon.

**Comment by assasinshark** [comment]
Ok, that would be great, I try using the button but takes me back to taking another picture.

**Comment by spinaki** [comment]
hi, I added a new V2 API -- with major fixes. Please see the readme. Can you please let me know if this bug still exists.

**Comment by spinaki** [comment]
closing since this has been fixed.
